In [1]:
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from bokeh.plotting import figure, output_file, show
from bokeh.models import (
    ColumnDataSource,
    HoverTool,
    LinearColorMapper,
    BasicTicker, LogTicker, ContinuousTicker, AdaptiveTicker,
    PrintfTickFormatter,
    ColorBar,
    FactorRange
)
import bokeh.palettes
from bokeh.transform import factor_cmap
from wordcloud import WordCloud, STOPWORDS
from math import floor
from bokeh.io import output_notebook

from bokeh.models import NumeralTickFormatter

In [3]:
data = pd.read_csv("../data/cleaned_data.csv")

In [4]:
data["profit"] = data["revenue"] - data["budget"]

In [5]:
data.head(3).transpose()

,0,1,2
budget,237000000,300000000,245000000
genres,"['Action', 'Adventure', 'Fantasy', 'Science Fi...","['Adventure', 'Fantasy', 'Action']","['Action', 'Adventure', 'Crime']"
keywords,"['culture clash', 'future', 'space war', 'spac...","['ocean', 'drug abuse', 'exotic island', 'east...","['spy', 'based on novel', 'secret agent', 'seq..."
original_language,en,en,en
overview,"In the 22nd century, a paraplegic Marine is di...","Captain Barbossa, long believed to be dead, ha...",A cryptic message from Bond’s past sends him o...
popularity,150.438,139.083,107.377
production_companies,"['Ingenious Film Partners', 'Twentieth Century...","['Walt Disney Pictures', 'Jerry Bruckheimer Fi...","['Columbia Pictures', 'Danjaq', 'B24']"
production_countries,"['United States of America', 'United Kingdom']",['United States of America'],"['United Kingdom', 'United States of America']"
release_date,2009-12-10,2007-05-19,2015-10-26
revenue,2787965087,961000000,880674609
runtime,162,169,148
spoken_languages,"['English', 'Español']",['English'],"['Français', 'English', 'Español', 'Italiano',..."
vote_average,7.2,6.9,6.3
vote_count,11800,4500,4466
title,Avatar,Pirates of the Caribbean: At World's End,Spectre
cast,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'cast_id': 1, 'character': 'James Bond', 'cr..."
crew,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{'credit_id': '54805967c3a36829b5002c41', 'de..."
actor1,Sam Worthington,Johnny Depp,Daniel Craig
actor2,Zoe Saldana,Orlando Bloom,Christoph Waltz
actor3,Sigourney Weaver,Keira Knightley,Léa Seydoux
director,James Cameron,Gore Verbinski,Sam Mendes
year,2009,2007,2015
month,12,5,10
day,10,19,26
dow,3,5,0
profit,2550965087,661000000,635674609

### test out some actor, director stuff

In [6]:
df = data

In [198]:
director_df = df.groupby('director', as_index=False)
director_df = director_df.mean()

In [199]:
name_counts = df['director'].value_counts().to_dict() # dictionary of director and number of rows/movies per
name_counts

{'Steven Spielberg': 27,
 'Woody Allen': 21,
 'Martin Scorsese': 20,
 'Clint Eastwood': 20,
 'Ridley Scott': 16,
 'Robert Rodriguez': 16,
 'Spike Lee': 16,
 'Steven Soderbergh': 15,
 'Renny Harlin': 15,
 'Tim Burton': 14,
 'Oliver Stone': 14,
 'Joel Schumacher': 13,
 'Ron Howard': 13,
 'Robert Zemeckis': 13,
 'Barry Levinson': 13,
 'Kevin Smith': 12,
 'Francis Ford Coppola': 12,
 'Tony Scott': 12,
 'Michael Bay': 12,
 'Brian De Palma': 12,
 'Richard Donner': 11,
 'Chris Columbus': 11,
 'Shawn Levy': 11,
 'Joel Coen': 11,
 'Richard Linklater': 11,
 'Sam Raimi': 11,
 'Bobby Farrelly': 11,
 'Rob Reiner': 11,
 'John McTiernan': 10,
 'John Carpenter': 10,
 'David Fincher': 10,
 'Wes Craven': 10,
 'Paul W.S. Anderson': 10,
 'Stephen Frears': 10,
 'Lasse Hallström': 9,
 'Dennis Dugan': 9,
 'M. Night Shyamalan': 9,
 'Rob Cohen': 9,
 'Peter Jackson': 9,
 'Tyler Perry': 9,
 'Phillip Noyce': 9,
 'Brett Ratner': 9,
 'Christopher Nolan': 8,
 'F. Gary Gray': 8,
 'Ivan Reitman': 8,
 'James Mangold': 8,
 'Martin Campbell': 8,
 'Adam Shankman': 8,
 'Marc Forster': 8,
 'Bryan Singer': 8,
 'Donald Petrie': 8,
 'Danny Boyle': 8,
 'David O. Russell': 8,
 'Neil Jordan': 8,
 'Antoine Fuqua': 8,
 'Alfred Hitchcock': 8,
 'Simon West': 8,
 'Garry Marshall': 8,
 'David Gordon Green': 8,
 'Roland Emmerich': 8,
 'Stephen Herek': 8,
 'Harold Ramis': 8,
 'Ang Lee': 8,
 'Quentin Tarantino': 8,
 'Jay Roach': 8,
 'Peter Segal': 7,
 'John Singleton': 7,
 'Barry Sonnenfeld': 7,
 'Todd Phillips': 7,
 'Tom Shadyac': 7,
 'James Wan': 7,
 'George Miller': 7,
 'Malcolm D. Lee': 7,
 'Gus Van Sant': 7,
 'David Cronenberg': 7,
 'Paul Greengrass': 7,
 'Sam Mendes': 7,
 'Guy Ritchie': 7,
 'James Ivory': 7,
 'James Cameron': 7,
 'Terry Gilliam': 7,
 'Wolfgang Petersen': 7,
 'Frank Oz': 7,
 'Edward Zwick': 7,
 'John Woo': 7,
 'Gore Verbinski': 7,
 'Mike Newell': 7,
 'Roger Donaldson': 7,
 'Tim Story': 7,
 'Kenneth Branagh': 7,
 'Jon Turteltaub': 7,
 'Zack Snyder': 7,
 'Doug Liman': 7,
 'Wes Anderson': 7,
 'Curtis Hanson': 7,
 'Frank Coraci': 7,
 'George A. Romero': 7,
 'Michael Moore': 6,
 'Joe Wright': 6,
 'Andy Fickman': 6,
 'Lilly Wachowski': 6,
 'Mark Waters': 6,
 'David Ayer': 6,
 'Darren Aronofsky': 6,
 'Gary Fleder': 6,
 'Andy Tennant': 6,
 'Brian Levant': 6,
 'Chris Weitz': 6,
 'Stanley Kubrick': 6,
 'Raja Gosnell': 6,
 'Michael Mann': 6,
 'Robert Luketic': 6,
 'Adam McKay': 6,
 'Atom Egoyan': 6,
 'Zhang Yimou': 6,
 'Peter Berg': 6,
 'Alejandro González Iñárritu': 6,
 'Joe Dante': 6,
 'McG': 6,
 'Brian Robbins': 6,
 'Catherine Hardwicke': 6,
 'Sidney Lumet': 6,
 'Robert Schwentke': 6,
 'Cameron Crowe': 6,
 'William Friedkin': 6,
 'Paul Thomas Anderson': 6,
 'Roman Polanski': 6,
 'Jon Favreau': 6,
 'Chuck Russell': 6,
 'Stephen Hopkins': 6,
 'Louis Leterrier': 6,
 'Peter Hyams': 6,
 'Mel Brooks': 6,
 'Taylor Hackford': 6,
 'Michael Winterbottom': 6,
 'Mike Nichols': 6,
 'Paul Schrader': 6,
 'Jaume Collet-Serra': 6,
 'Guy Hamilton': 6,
 'Guillermo del Toro': 5,
 'David R. Ellis': 5,
 'David Koepp': 5,
 'John Whitesell': 5,
 'Alexander Payne': 5,
 "Gavin O'Connor": 5,
 'Larry Charles': 5,
 'Nancy Meyers': 5,
 'Kevin Reynolds': 5,
 'Luc Besson': 5,
 'John Landis': 5,
 'Stephen Daldry': 5,
 'Richard LaGravenese': 5,
 'Mike Leigh': 5,
 'Jason Friedberg': 5,
 'Wayne Wang': 5,
 'Justin Lin': 5,
 'Ben Stiller': 5,
 'Alex Proyas': 5,
 'Miguel Arteta': 5,
 'Scott Hicks': 5,
 'George Lucas': 5,
 'Richard Lester': 5,
 'Lee Tamahori': 5,
 'Michael Polish': 5,
 'Lawrence Kasdan': 5,
 'Jonathan Liebesman': 5,
 'Bill Condon': 5,
 'David Lynch': 5,
 'Brian Helgeland': 5,
 'Fred Zinnemann': 5,
 'Jean-Pierre Jeunet': 5,
 'Anne Fletcher': 5,
 'Frank Capra': 5,
 'Jon M. Chu': 5,
 'Paul Weitz': 5,
 'Tim Hill': 5,
 'Paul Verhoeven': 5,
 'Jan de Bont': 5,
 'Peter Chelsom': 5,
 'Nicholas Stoller': 5,
 'Jason Reitman': 5,
 'Uwe Boll': 5,
 'Gary Winick': 5,
 'Nicole Holofcener': 5,
 'Mira Nair': 5,
 'John Frankenheimer': 5,
 'Rod Lurie': 5,
 'Brad Anderson': 5,
 'Jonathan Demme': 5,
 'Tom Tykwer': 5,
 'Norman Jewison': 5,
 'Tobe Hooper': 5,
 'Judd Apatow': 5,
 'Andrzej Bartkowiak': 5,
 'Rob Marshall': 5,
 'Les Mayfield': 5,
 'Andrew Adamson': 5,
 'John Glen': 5,
 'Kirk Jones': 5,
 'Francis Lawrence': 5,
 'John Madden': 5,
 'George Clooney': 5,
 'Rob Minkoff': 5,
 'Steve Miner': 5,
 'David Zucker': 5,
 'Sydney Pollack': 5,
 'Michael Apted': 5,
 'Robert Redford': 5,
 'Andrew Niccol': 5,
 'Darren Lynn Bousman': 5,
 'Kenny Ortega': 5,
 'Michael Caton-Jones': 4,
 'Tarsem Singh': 4,
 'David Lean': 4,
 'James McTeigue': 4,
 'Betty Thomas': 4,
 'Carlos Saldanha': 4,
 'Eric Darnell': 4,
 'David Frankel': 4,
 'Jonathan Frakes': 4,
 'Richard Attenborough': 4,
 'Alex Kendrick': 4,
 'Jerry Zucker': 4,
 'Steve Oedekerk': 4,
 'Robert Wise': 4,
 'Randall Wallace': 4,
 'Harold Becker': 4,
 'Alejandro Amenábar': 4,
 'Bille Woodruff': 4,
 'John Lee Hancock': 4,
 'John Moore': 4,
 'Paul Feig': 4,
 'Edgar Wright': 4,
 'Andrew Davis': 4,
 'Luke Greenfield': 4,
 'Jeff Nichols': 4,
 'Bob Clark': 4,
 'Sam Weisman': 4,
 'Jeff Tremaine': 4,
 'David Bowers': 4,
 'Steven Brill': 4,
 'Nicolas Winding Refn': 4,
 'Iain Softley': 4,
 'Spike Jonze': 4,
 'Gavin Hood': 4,
 'Penny Marshall': 4,
 'Richard Brooks': 4,
 'Sergio Leone': 4,
 'David Twohy': 4,
 'Ron Shelton': 4,
 'Patrick Lussier': 4,
 'Jay Chandrasekhar': 4,
 'Stephen Sommers': 4,
 'Hugh Wilson': 4,
 'Burr Steers': 4,
 'Roger Spottiswoode': 4,
 'Alexandre Aja': 4,
 'Hayao Miyazaki': 4,
 'Sofia Coppola': 4,
 'Jonathan Mostow': 4,
 'Terence Young': 4,
 'Matthew Vaughn': 4,
 'Rick Famuyiwa': 4,
 'Andrew Fleming': 4,
 'John Stockwell': 4,
 'Brian Taylor': 4,
 'Frank Marshall': 4,
 'Mark L. Lester': 4,
 'Vincenzo Natali': 4,
 'Dennie Gordon': 4,
 'Brad Bird': 4,
 'Neil Burger': 4,
 'Richard Fleischer': 4,
 'Keenen Ivory Wayans': 4,
 'Matt Reeves': 4,
 'Martin Brest': 4,
 'Peter Hewitt': 4,
 'J.J. Abrams': 4,
 'John Dahl': 4,
 'Phil Lord': 4,
 'John Sayles': 4,
 'Sean Anders': 4,
 'Walt Becker': 4,
 'Mike Mitchell': 4,
 'Steve Carr': 4,
 'Walter Hill': 4,
 'Craig Gillespie': 4,
 'Peter Weir': 4,
 'Rob Bowman': 4,
 'Peter Howitt': 4,
 'John Lasseter': 4,
 'David Wain': 4,
 'Baz Luhrmann': 4,
 'David Dobkin': 4,
 'Jean-Jacques Annaud': 4,
 'Jonathan Levine': 4,
 'Alfonso Cuarón': 4,
 'Bruce Beresford': 4,
 'Edward Burns': 4,
 'James Gray': 4,
 'Ronny Yu': 4,
 'Andrew Stanton': 4,
 'Jay Duplass': 4,
 'Mike Judge': 4,
 'Sam Peckinpah': 4,
 'Jonathan Lynn': 4,
 'Peyton Reed': 4,
 'Amy Heckerling': 4,
 'Russell Mulcahy': 4,
 'D.J. Caruso': 4,
 'Gabriele Muccino': 4,
 'Peter Cattaneo': 4,
 'Mikael Håfström': 4,
 'Timur Bekmambetov': 4,
 'Jon Amiel': 4,
 'Jaume Balagueró': 4,
 'Anthony Russo': 4,
 'Jake Kasdan': 4,
 'Dean Parisot': 4,
 'Brad Silberling': 4,
 'Rob Zombie': 4,
 'Simon Wincer': 4,
 'George Tillman, Jr.': 4,
 'John Ford': 4,
 'Nick Cassavetes': 4,
 'James Wong': 4,
 'Scott Derrickson': 4,
 'Ken Kwapis': 4,
 'Christopher Guest': 4,
 'Frank Darabont': 4,
 'Terrence Malick': 4,
 'John Erick Dowdle': 4,
 'Irwin Winkler': 4,
 'Shane Meadows': 4,
 'Joe Johnston': 4,
 'Pierre Morel': 4,
 'Adrian Lyne': 4,
 'Billy Wilder': 4,
 'Michel Gondry': 4,
 'James Cox': 3,
 'Scott Cooper': 3,
 'Jean-Marie Poiré': 3,
 'Nora Ephron': 3,
 'David Yates': 3,
 'David Slade': 3,
 'Jon Knautz': 3,
 'Leonard Nimoy': 3,
 'Lewis Gilbert': 3,
 'Lars von Trier': 3,
 'Eli Roth': 3,
 'Walter Salles': 3,
 'Thomas Vinterberg': 3,
 'Michael Ritchie': 3,
 'Julie Taymor': 3,
 'Albert Hughes': 3,
 'Kathryn Bigelow': 3,
 'John Schlesinger': 3,
 'Alan Parker': 3,
 'Gurinder Chadha': 3,
 'Jodie Foster': 3,
 'Boaz Yakin': 3,
 'Tony Kaye': 3,
 'Kevin Macdonald': 3,
 'Kimberly Peirce': 3,
 'Olivier Megaton': 3,
 'Ron Underwood': 3,
 'Richard Benjamin': 3,
 'Nicholas Hytner': 3,
 'Don Michael Paul': 3,
 'Douglas McGrath': 3,
 'Brad Furman': 3,
 'Noah Baumbach': 3,
 'Kevin Rodney Sullivan': 3,
 'Charles Martin Smith': 3,
 'Charles Ferguson': 3,
 'Chris Sanders': 3,
 'Elia Kazan': 3,
 'Anand Tucker': 3,
 'Tom Dey': 3,
 'John Pasquin': 3,
 'J.C. Chandor': 3,
 'Stephen T. Kay': 3,
 'Howard Deutch': 3,
 'Rawson Marshall Thurber': 3,
 'Thor Freudenthal': 3,
 'James Bobin': 3,
 'Kevin Costner': 3,
 'Marc Webb': 3,
 'Michael Schultz': 3,
 'Greg Mottola': 3,
 'Chris Wedge': 3,
 'John Milius': 3,
 'Patricia Riggen': 3,
 'Mike Binder': 3,
 'Roland Joffé': 3,
 'Morgan Spurlock': 3,
 'Richard Shepard': 3,
 'Jean-Marc Vallée': 3,
 'Christopher McQuarrie': 3,
 'Danny DeVito': 3,
 'James DeMonaco': 3,
 'Mark Pellington': 3,
 'Stephen Chow': 3,
 'Nimród Antal': 3,
 'Jeff Wadlow': 3,
 'Brad Peyton': 3,
 'Richard Curtis': 3,
 'Ron Clements': 3,
 'Mark Dindal': 3,
 'Miloš Forman': 3,
 'John Hamburg': 3,
 'Will Gluck': 3,
 'Neill Blomkamp': 3,
 'Barbra Streisand': 3,
 'Griffin Dunne': 3,
 'Davis Guggenheim': 3,
 'Anthony Minghella': 3,
 'Duncan Jones': 3,
 'John Schultz': 3,
 'Neil Marshall': 3,
 'Richard Kelly': 3,
 'Charles Herman-Wurmfeld': 3,
 'Henry Joost': 3,
 'Michael Tiddes': 3,
 'Mel Gibson': 3,
 'Joss Whedon': 3,
 'Don Coscarelli': 3,
 'James Foley': 3,
 'Reginald Hudlin': 3,
 'Jim Sheridan': 3,
 'Conrad Vernon': 3,
 'John Cameron Mitchell': 3,
 'Fernando Meirelles': 3,
 'Jay Russell': 3,
 'Michael Lehmann': 3,
 'Paul Haggis': 3,
 'Tom Hooper': 3,
 'Jonathan Glazer': 3,
 'Niki Caro': 3,
 'Victor Salva': 3,
 'Seth MacFarlane': 3,
 'Steve Pink': 3,
 'Robert Altman': 3,
 'Robert Iscove': 3,
 'John Boorman': 3,
 'Len Wiseman': 3,
 'Roger Kumble': 3,
 'David Hand': 3,
 'William Brent Bell': 3,
 'George Sidney': 3,
 'Shana Feste': 3,
 'Angelina Jolie': 3,
 'Todd Haynes': 3,
 'Michael Haneke': 3,
 'Marc Lawrence': 3,
 'Todd Solondz': 3,
 'Jared Hess': 3,
 'Kelly Reichardt': 3,
 'Victor Fleming': 3,
 'Roger Michell': 3,
 'Gina Prince-Bythewood': 3,
 'Franklin J. Schaffner': 3,
 'Anton Corbijn': 3,
 'Simon Wells': 3,
 'Shekhar Kapur': 3,
 'Trey Parker': 3,
 'Michael Curtiz': 3,
 'Warren Beatty': 3,
 'Mimi Leder': 3,
 'Pete Docter': 3,
 'Lloyd Kaufman': 3,
 'Daniel Espinosa': 3,
 'Ruben Fleischer': 3,
 'John Hillcoat': 3,
 'Peter Sollett': 3,
 'Randal Kleiser': 3,
 'Gregory Hoblit': 3,
 'Neil LaBute': 3,
 'Park Chan-wook': 3,
 'Carl Franklin': 3,
 'James L. Brooks': 3,
 'Stefan Ruzowitzky': 3,
 'Glenn Ficarra': 3,
 'Jesse Dylan': 3,
 'Thomas Carter': 3,
 'Oliver Parker': 3,
 'Denis Villeneuve': 3,
 'Chris Rock': 3,
 'Michael Hoffman': 3,
 'Gary Ross': 3,
 'King Vidor': 3,
 'Brian Trenchard-Smith': 3,
 'Joe Carnahan': 3,
 'Genndy Tartakovsky': 3,
 'Wong Kar-wai': 3,
 'Tony Gilroy': 3,
 'John Waters': 3,
 'Jon Avnet': 3,
 'James Gunn': 3,
 'Breck Eisner': 3,
 'Seth Gordon': 3,
 'Paul McGuigan': 3,
 'Joe Nussbaum': 3,
 'Richard Loncraine': 3,
 'George P. Cosmatos': 3,
 'Kasi Lemmons': 3,
 'Jane Campion': 3,
 'Baltasar Kormákur': 3,
 'Dominic Sena': 3,
 'Takashi Shimizu': 2,
 'Charlie Kaufman': 2,
 'Tony Richardson': 2,
 'Xavier Gens': 2,
 'Bob Saget': 2,
 'David Schwimmer': 2,
 'Paul Andrew Williams': 2,
 'Sam Miller': 2,
 'Stanley Kramer': 2,
 'Victor Nunez': 2,
 'Steven Shainberg': 2,
 'Mikael Salomon': 2,
 'Charles Stone III': 2,
 'Nick Park': 2,
 'Courtney Solomon': 2,
 'Glen Morgan': 2,
 'Ronald F. Maxwell': 2,
 'Bennett Miller': 2,
 'Tommy Wirkola': 2,
 'Kevin Spacey': 2,
 'Sheldon Lettich': 2,
 'Juan José Campanella': 2,
 'Jon Lucas': 2,
 'Marco Kreuzpaintner': 2,
 'Irvin Kershner': 2,
 'John Herzfeld': 2,
 'Daniel Lee': 2,
 'Christopher Smith': 2,
 'Danny Pang': 2,
 'Bill Paxton': 2,
 'Cédric Klapisch': 2,
 'Billy Ray': 2,
 'Jean-Paul Rappeneau': 2,
 'Whit Stillman': 2,
 'DJ Pooh': 2,
 'Ariel Vromen': 2,
 'Werner Herzog': 2,
 'Nicholas Meyer': 2,
 'Tom McCarthy': 2,
 'Bart Freundlich': 2,
 'Pan Nalin': 2,
 'Steve Boyum': 2,
 'Preston A. Whitmore II': 2,
 'Elizabeth Allen Rosenbaum': 2,
 'Tony Goldwyn': 2,
 'Craig Brewer': 2,
 'Walter Lang': 2,
 'Stephen Norrington': 2,
 'Michael Rymer': 2,
 'Mark Rosman': 2,
 'Steve Beck': 2,
 'Anne Fontaine': 2,
 'Uli Edel': 2,
 'Tate Taylor': 2,
 'Fenton Bailey': 2,
 'Jon Hurwitz': 2,
 'Douglas Aarniokoski': 2,
 'Luis Mandoki': 2,
 'Chris Stokes': 2,
 'Karyn Kusama': 2,
 'Yash Chopra': 2,
 'Richard Kwietniowski': 2,
 'Dave Green': 2,
 'Craig Moss': 2,
 'Rob Letterman': 2,
 'François Ozon': 2,
 'Eric Brevig': 2,
 'Kenneth Lonergan': 2,
 'Michael Mayer': 2,
 'Thomas Bezucha': 2,
 'Rupert Wyatt': 2,
 'Larry Clark': 2,
 'Clare Kilner': 2,
 'Michael Dowse': 2,
 'John Turturro': 2,
 'Sylvain White': 2,
 'Kurt Wimmer': 2,
 'Mary Lambert': 2,
 'Phyllida Lloyd': 2,
 'Jeb Stuart': 2,
 'Todd Graff': 2,
 'Daniel Barnz': 2,
 'Frederik Du Chau': 2,
 'Paul Gross': 2,
 'Jamie Blanks': 2,
 'Michael O. Sajbel': 2,
 'Blake Edwards': 2,
 'Isabel Coixet': 2,
 'Karey Kirkpatrick': 2,
 'Scott Stewart': 2,
 'Oren Peli': 2,
 'Bernardo Bertolucci': 2,
 'John Curran': 2,
 'Steven Quale': 2,
 'James Watkins': 2,
 'Callie Khouri': 2,
 'Mike Flanagan': 2,
 'Carol Reed': 2,
 'Seth Rogen': 2,
 'Laurent Tirard': 2,
 'Kim Jee-woon': 2,
 'Tommy Lee Jones': 2,
 'Joe Swanberg': 2,
 'Tom Hanks': 2,
 'Brian Gibson': 2,
 'Patrick Stettner': 2,
 'Andrew Bujalski': 2,
 'Nick Murphy ': 2,
 'Carroll Ballard': 2,
 'Zach Braff': 2,
 'Bille August': 2,
 'Daisy von Scherler Mayer': 2,
 'Rodrigo García': 2,
 'Jerry Jameson': 2,
 'Brett Leonard': 2,
 'George Armitage': 2,
 'Gaspar Noé': 2,
 'Pete Travis': 2,
 'Alejandro Monteverde': 2,
 'Tamra Davis': 2,
 'Zal Batmanglij': 2,
 'Mark Brown': 2,
 'Phil Joanou': 2,
 'Shari Springer Berman': 2,
 'Josh Trank': 2,
 'Christian Alvart': 2,
 'Léa Pool': 2,
 'Olivier Assayas': 2,
 'Christopher Cain': 2,
 'Henry Selick': 2,
 'Jeremy Saulnier': 2,
 'George Roy Hill': 2,
 'Bob Fosse': 2,
 'David McNally': 2,
 'Chris Noonan': 2,
 'Andrew Dominik': 2,
 'Akira Kurosawa': 2,
 'Lone Scherfig': 2,
 'Adam Rifkin': 2,
 'Peter Webber': 2,
 'Billy Bob Thornton': 2,
 'Vicky Jenson': 2,
 'Mike Cahill': 2,
 'Bruce McCulloch': 2,
 'Chris Kentis': 2,
 'C. Jay Cox': 2,
 'Justin Chadwick': 2,
 'Colin Strause': 2,
 'Patrick Read Johnson': 2,
 'Sean McNamara': 2,
 'Troy Duffy': 2,
 'Stephan Elliott': 2,
 'Danny Leiner': 2,
 'Paweł Pawlikowski': 2,
 'Costa-Gavras': 2,
 'Julian Jarrold': 2,
 'Steve Buscemi': 2,
 'Alan J. Pakula': 2,
 'Craig Mazin': 2,
 'Deepa Mehta': 2,
 'Ben Wheatley': 2,
 'Steve Martino': 2,
 'Sergei Bodrov': 2,
 'Michael Cimino': 2,
 'Tamara Jenkins': 2,
 'Andrew Bergman': 2,
 'Kevin Munroe': 2,
 'Mitch Davis': 2,
 'Josh Gordon': 2,
 'Ted Post': 2,
 'William Malone': 2,
 'Tim Johnson': 2,
 'Ti West': 2,
 'Shim Hyung-Rae': 2,
 'Peter Hedges': 2,
 'Vadim Perelman': 2,
 'Jack Smight': 2,
 'Jim Gillespie': 2,
 'Bob Odenkirk': 2,
 'Marcus Raboy': 2,
 'Gil Kenan': 2,
 'Travis Legge': 2,
 'Susanna White': 2,
 'Chris Williams': 2,
 'Eric Valette': 2,
 'Julie Anne Robinson': 2,
 'Joseph Zito': 2,
 'David DeCoteau': 2,
 'Oliver Hirschbiegel': 2,
 'David Mamet': 2,
 'Jamie Babbit': 2,
 'Bong Joon-ho': 2,
 'Barbet Schroeder': 2,
 'Ben Stassen': 2,
 'Michael Corrente': 2,
 'Morten Tyldum': 2,
 'Ed Harris': 2,
 'Rodrigo Cortés': 2,
 'Stacy Peralta': 2,
 'Greg Harrison': 2,
 'Mick Jackson': 2,
 'Teddy Chan': 2,
 'Angela Robinson': 2,
 'Barry Cook': 2,
 'Martin Ritt': 2,
 'David Hackl': 2,
 'Sanaa Hamri': 2,
 'Mark Herman': 2,
 'Tim Robbins': 2,
 'Salim Akil': 2,
 'Mike Mills': 2,
 'Andrei Konchalovsky': 2,
 'Stephen Gaghan': 2,
 'Chris Koch': 2,
 'Alan Taylor': 2,
 'Akiva Schaffer': 2,
 'Karan Johar': 2,
 'Kevin Bray': 2,
 'George Gallo': 2,
 'Lee Daniels': 2,
 'Jon Gunn': 2,
 'Gil Junger': 2,
 'Deborah Kaplan': 2,
 'John Polson': 2,
 'Stewart Raffill': 2,
 'Chris Miller': 2,
 'Simon Curtis': 2,
 'Eric Bross': 2,
 'Joe Roth': 2,
 'William Dear': 2,
 'Michael Cuesta': 2,
 'Sam Taylor-Johnson': 2,
 'Ben Affleck': 2,
 'Howard Zieff': 2,
 'John Huston': 2,
 'John Carney': 2,
 'Mario Van Peebles': 2,
 'Vincent Gallo': 2,
 'Julian Gilbey': 2,
 'Camille Delamarre': 2,
 'Denzel Washington': 2,
 'Jill Sprecher': 2,
 'Roger Avary': 2,
 'Nick Love': 2,
 'Jacques Perrin': 2,
 'Jimmy Hayward': 2,
 'Mike Figgis': 2,
 'Harald Zwart': 2,
 'J.B. Rogers': 2,
 'Michael Lembeck': 2,
 'Ol Parker': 2,
 'Nelson McCormick': 2,
 'Claude Chabrol': 2,
 'Ryan Coogler': 2,
 'Clark Johnson': 2,
 'Gary Trousdale': 2,
 'Michael Landon Jr.': 2,
 'Guillaume Canet': 2,
 'Colin Trevorrow': 2,
 'Luis Llosa': 2,
 'Gregor Jordan': 2,
 'Jennifer Yuh Nelson': 2,
 'Darren Stein': 2,
 'Ava DuVernay': 2,
 'Joseph Kahn': 2,
 'Ryan Fleck': 2,
 'Jessie Nelson': 2,
 'Ira Sachs': 2,
 'Rian Johnson': 2,
 'Nigel Cole': 2,
 'John G. Avildsen': 2,
 'Pierre Coffin': 2,
 'Terry Zwigoff': 2,
 'Jake Schreier': 2,
 'Mathieu Kassovitz': 2,
 'Lynne Ramsay': 2,
 'Lee Toland Krieger': 2,
 'Jeannot Szwarc': 2,
 'Tom Holland': 2,
 'Geoffrey Sax': 2,
 'E. Elias Merhige': 2,
 'Robert Greenwald': 2,
 'Brian Koppelman': 2,
 'William Kaufman': 2,
 'Ryan Murphy': 2,
 'Philip Kaufman': 2,
 'Todd Field': 2,
 'Patricia Cardoso': 2,
 'Karen Moncrieff': 2,
 "Tommy O'Haver": 2,
 'Matty Rich': 2,
 'Mark Romanek': 2,
 'Mark Steven Johnson': 2,
 'Christian Duguay': 2,
 'Kevin Lima': 2,
 'Ben Falcone': 2,
 'Martin Lawrence': 2,
 'Sean Penn': 2,
 'Kurt Hale': 2,
 'Ken Scott': 2,
 'Tim McCanlies': 2,
 'Robert Harmon': 2,
 'Joel Paul Reisig': 2,
 'Joel Zwick': 2,
 'Steven Zaillian': 2,
 'Kevin Greutert': 2,
 'Vic Sarin': 2,
 'Steve Rash': 2,
 'Katsuhiro Ōtomo': 2,
 'Craig R. Baxley': 2,
 'John Luessenhop': 2,
 'Richard Eyre': 2,
 'Gillian Armstrong': 2,
 'James Marsh': 2,
 'John Wells': 2,
 'Ernie Barbarash': 2,
 'Tom Vaughan': 2,
 'Jesse Peretz': 2,
 'Florian Henckel von Donnersmarck': 2,
 'Mike Tollin': 2,
 'John A. Davis': 2,
 'Martin McDonagh': 2,
 'Ning Hao': 2,
 'Steve James': 2,
 'Rachel Talalay': 2,
 'Stuart Gordon': 2,
 'Derek Cianfrance': 2,
 'Mark Osborne': 2,
 'John R. Leonetti': 2,
 'Juan Antonio Bayona': 2,
 'José Padilha': 2,
 'Stuart Baird': 2,
 'David Raynr': 2,
 'Allison Anders': 2,
 'Fred Wolf': 2,
 'Lawrence Guterman': 2,
 'Steve McQueen': 2,
 'Jonas Åkerlund': 2,
 'Rowan Joffe': 2,
 'Julian Schnabel': 2,
 'George Hickenlooper': 2,
 'Rowdy Herrington': 2,
 'Gary Goldman': 2,
 'James Toback': 2,
 'Wes Ball': 2,
 'Jean-Luc Godard': 2,
 'Wayne Kramer': 2,
 'Kevin Tancharoen': 2,
 'Dwight H. Little': 2,
 'Stuart Gillard': 2,
 'Shane Black': 2,
 'Joseph Kosinski': 2,
 'Richard Schenkman': 2,
 'Kevin Allen': 2,
 'Danny Cannon': 2,
 'David Leland': 2,
 'Sylvester Stallone': 2,
 'Richard Glatzer': 2,
 'Hugh Hudson': 2,
 'Bob Rafelson': 2,
 'Morgan J. Freeman': 2,
 'Norton Virgien': 2,
 'David S. Goyer': 2,
 'J. Lee Thompson': 2,
 'Michael Radford': 2,
 'Clark Baker': 1,
 'Stefan C. Schaefer': 1,
 'Dagur Kári': 1,
 'Jack Conway': 1,
 'Jamie Travis': 1,
 'Gilles Paquet-Brenner': 1,
 'Michael Hoffman Jr.': 1,
 'Cary Bell': 1,
 'Dan St. Pierre': 1,
 'Kirk Wong': 1,
 'Lance Rivera': 1,
 'Malcolm Goodwin': 1,
 'Noam Murro': 1,
 "Damien O'Donnell": 1,
 'Adam Marcus': 1,
 'Christopher Scott Cherot': 1,
 'Joshua Logan': 1,
 'Jake Paltrow': 1,
 'Andy García': 1,
 'Martyn Pick': 1,
 'Maggie Greenwald': 1,
 'Jerome Elston Scott': 1,
 'John Carl Buechler': 1,
 'Terry George': 1,
 'Mikel Rueda': 1,
 'Michael Dougherty': 1,
 'Kim Farrant': 1,
 'Tom Walsh': 1,
 'Shinji Aramaki': 1,
 'Arie Posin': 1,
 'Maria Maggenti': 1,
 'Nicholaus Goossen': 1,
 'Ritesh Batra': 1,
 'Maggie Carey': 1,
 'Tay Garnett': 1,
 'Katherine Brooks': 1,
 'Chris Morris': 1,
 'R.J. Cutler': 1,
 'Johnnie To': 1,
 'Floria Sigismondi': 1,
 'Janusz Kamiński': 1,
 'Joe Cornish': 1,
 'Ted Demme': 1,
 'John Reinhardt': 1,
 'Gary David Goldberg': 1,
 'Nacho Vigalondo': 1,
 'Francesca Gregorini': 1,
 'Peter MacDonald': 1,
 'Gregory Widen': 1,
 'Joseph Green': 1,
 'Travis Zariwny': 1,
 'Patrick Creadon': 1,
 'Alison Maclean': 1,
 'Ben Sharpsteen': 1,
 'Lu Chuan': 1,
 'George Nolfi': 1,
 'Mel Stuart': 1,
 'Warren Sheppard': 1,
 'Gary Nelson': 1,
 'Gabriela Tagliavini': 1,
 'Neil Mcenery-West': 1,
 'Laurie Collyer': 1,
 'Jacob Aaron Estes': 1,
 'Yorgos Lanthimos': 1,
 'Jonathan Caouette': 1,
 'James Ponsoldt': 1,
 'Jonathan Dayton': 1,
 'Frank LaLoggia': 1,
 'Daniel Taplitz': 1,
 'John Maybury': 1,
 'John McNaughton': 1,

In [200]:
director_df['film_count'] = director_df['director'].map(name_counts) # match the film count to the director

In [201]:
director_df.head()

,director,budget,popularity,revenue,runtime,vote_average,vote_count,year,month,day,dow,profit,film_count
0,Aaron Hann,0.0,6.752141,0.0,87.0,6.0,333.0,2015.0,10.0,2.0,4.0,0.0,1
1,Aaron Schneider,7500000.0,6.557643,0.0,103.0,6.5,100.0,2010.0,1.0,22.0,4.0,-7500000.0,1
2,Abel Ferrara,12500000.0,2.950618,1227324.0,99.0,7.3,31.0,1996.0,1.0,26.0,4.0,-11272676.0,1
3,Adam Brooks,0.0,29.173266,55447968.0,112.0,6.7,620.0,2008.0,2.0,8.0,4.0,55447968.0,1
4,Adam Carolla,1500000.0,0.859014,0.0,97.0,6.6,8.0,2015.0,3.0,6.0,4.0,-1500000.0,1

In [202]:
director_df.sort_values('profit', ascending=False, inplace=True)

In [203]:
director_df['director+count'] = director_df['director'].map(str) + " (" + director_df['film_count'].map(str) + ")"

In [204]:
director_df.head()

,director,budget,popularity,revenue,runtime,vote_average,vote_count,year,month,day,dow,profit,film_count,director+count
318,Chris Buck,1.500000e+08,165.125366,1.274219e+09,102.000000,7.300000,5295.000000,2013.000000,11.000000,27.0,2.000000,1.124219e+09,1,Chris Buck (1)
1281,Kyle Balda,7.400000e+07,875.581305,1.156731e+09,91.000000,6.400000,4571.000000,2015.000000,6.000000,17.0,2.000000,1.082731e+09,1,Kyle Balda (1)
1305,Lee Unkrich,2.000000e+08,59.995418,1.066970e+09,103.000000,7.600000,4597.000000,2010.000000,6.000000,16.0,2.000000,8.669697e+08,1,Lee Unkrich (1)
1172,Joss Whedon,1.796667e+08,108.038933,9.879437e+08,134.333333,7.366667,6602.333333,2010.666667,5.333333,24.0,2.333333,8.082770e+08,3,Joss Whedon (3)
332,Chris Renaud,7.500000e+07,31.482872,8.759583e+08,87.000000,5.900000,3462.000000,2016.000000,6.000000,18.0,5.000000,8.009583e+08,1,Chris Renaud (1)

In [205]:
dir_means = director_df[['director+count',  'film_count', 'profit']]

In [206]:
dir_means.head()

        director+count  film_count        profit
318     Chris Buck (1)           1  1.124219e+09
1281    Kyle Balda (1)           1  1.082731e+09
1305   Lee Unkrich (1)           1  8.669697e+08
1172   Joss Whedon (3)           3  8.082770e+08
332   Chris Renaud (1)           1  8.009583e+08

In [207]:
dir_subset = director_df[director_df['film_count'] > 5]

### average profit and movie rating for directors who have produced more than 5 movies

In [208]:
top10pro = dir_subset.sort_values(ascending = False, by = 'profit')[['director+count','profit']].head(10)
top10pro

             director+count        profit
880       James Cameron (7)  7.338099e+08
1731      Peter Jackson (9)  5.784048e+08
360   Christopher Nolan (8)  4.028104e+08
1475       Michael Bay (12)  3.685437e+08
1110        Jon Favreau (6)  3.003090e+08
907           James Wan (7)  2.988021e+08
765      Gore Verbinski (7)  2.957162e+08
1965         Sam Mendes (7)  2.927927e+08
320     Chris Columbus (11)  2.816938e+08
2102  Steven Spielberg (27)  2.770331e+08

In [209]:
top10rat = dir_subset.sort_values(ascending = False, by = 'vote_average')[['director+count', 'vote_average']].head(10)
top10rat

                       director+count  vote_average
360             Christopher Nolan (8)      7.800000
1772            Quentin Tarantino (8)      7.775000
2049              Stanley Kubrick (6)      7.683333
2286                 Wes Anderson (7)      7.414286
486                David Fincher (10)      7.340000
1731                Peter Jackson (9)      7.333333
880                 James Cameron (7)      7.328571
1426             Martin Scorsese (20)      7.295000
39    Alejandro González Iñárritu (6)      7.233333
1698         Paul Thomas Anderson (6)      7.216667

In [210]:
y=top10pro['director+count']

In [211]:
y

880         James Cameron (7)
1731        Peter Jackson (9)
360     Christopher Nolan (8)
1475         Michael Bay (12)
1110          Jon Favreau (6)
907             James Wan (7)
765        Gore Verbinski (7)
1965           Sam Mendes (7)
320       Chris Columbus (11)
2102    Steven Spielberg (27)
Name: director+count, dtype: object

In [212]:
import pandas as pd
import numpy as np
import plotly as py
import plotly.graph_objs as go
import ipywidgets as widgets
import datetime

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.figure_factory as ff

py.offline.init_notebook_mode(connected=True)

from math import floor
from plotly import tools
from plotly.graph_objs import *

In [213]:
import plotly.plotly as py
import plotly.graph_objs as go

data = [go.Bar(
            x=top10pro['profit'],
            y=top10pro['director+count'],
            orientation = 'h',
            marker=dict(
            color='rgb(127,205,187)'
        )
)]

layout = dict(
        title='Average Profit for Directors who have directed more than 5 movies',
        margin=go.Margin(
        l=210,
        r=100,
        pad=1),
        xaxis=dict(
            title='Average Profit'
        ),
    
        yaxis=dict(
            title='&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Director (Number of Movies)',
            tickfont=dict(
                size=12,
            )
        )
    
    )
    

fig = go.Figure(data = data, layout = layout)

iplot(fig)

In [214]:
import plotly.plotly as py
import plotly.graph_objs as go

data = [go.Bar(
            x=top10rat['vote_average'],
            y=top10rat['director+count'],
            orientation = 'h',
            marker=dict(
            color='rgb(67,162,202)'
        )
)]

layout = dict(
        title='Average Movie Rating for Directors who have directed more than 5 movies',
        margin=go.Margin(
        l=210,
        r=100,
        b=100,
        t=100,
        pad=1),
            xaxis=dict(
            title='Average Rating'
        ),
    
        yaxis=dict(
            title='&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Director (Number of Movies)',
            tickfont=dict(
                size=12,
            )
        )
    
    )

fig = go.Figure(data = data, layout = layout)

iplot(fig)